name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          config: ".markdownlint.yml"
          args: "content/posts/*.md"
